---

- name: "configuration management EKS."
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - cluster-deploy
    - cluster-service