---
- name: "Download The AWS CLI Archive"
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  args:
    chdir: $HOME

- name: "Unzip the AWS CLI Archive"
  shell: unzip awscliv2.zip
  args:
    chdir: $HOME

- name: "Install the AWS CLI"
  shell: ./aws/install
  args:
    chdir: $HOME

- name: Set the aws Authenticate
  become: true
  shell: |
    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    aws configure set default.region $AWS_DEFAULT_REGION